name: coffee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-220.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  mask_text_input_formatter: ^2.5.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/



  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-BlackItalic.ttf
        - asset: assets/fonts/DMSans-Black.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-LightItalic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
        - asset: assets/fonts/DMSans-ThinItalic.ttf
